---
- name: Ensure Samba packages are installed
  ansible.builtin.package:
    name:
      - samba
      - avahi
      - dbus
    state: latest

- name: Samba configuration
  template:
    src: templates/smb.conf.j2
    dest: /etc/samba/smb.conf
  notify: restart samba

- name: Ensure Linux user exists
  user:
    name: "{{ timecapsule_username }}"

- name: Update smbpasswd
  shell: |
    set -o pipefail
    (echo '{{ timecapsule_password }}'; echo '{{ timecapsule_password }}') | smbpasswd -s -a {{ timecapsule_username }}

- name: Ensure timecapsule folder exists
  file:
    path: "{{ timecapsule_folder }}"
    state: directory
    owner: "{{ timecapsule_username }}"
    group: "{{ timecapsule_username }}"
    mode: "0700"

- name: Ensure services are started and enabled
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - samba
    - dbus
    - avahi-daemon
